// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Apache Ignite With Spring Session

== Overview


Apache Ignite Spring Session integration provides SessionRepository and ReactiveSessionRepository implementation and configuration support. Spring Session simplifies support for clustered sessions without being tied to an application container specific solution.


== Maven Configuration

Add the `ignite-spring-session-ext` extension to your Maven to use your Ignite servers or clients with Spring Session.

The extension can be added with Maven as follows:

[tabs]
--
tab:pom.xml[]
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session-core</artifactId>
  </dependency>
  <dependency>
    <groupId>org.apache.ignite</groupId>
    <artifactId>ignite-spring-session-ext</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependencies>
----
--

=== Set Ignite Up Programmatically

To expose Spring Sessions to Ignite:

- Add the `@EnableIgniteHttpSession` annotation to the class that configures Ignite session.
- Add the `@SpringSessionIgnite` annotation to your Ignite instance.

After you add these annotations, Spring Session will use Ignite as data storage for sessions.  For example, here is how you can create a simple controller:

[source,java]
----
@Controller
public class SampleController {
    @GetMapping("/")
    public String SessionId(HttpSession session) {
        return session.getId();
    }
}
----



== Extended Example

You can find an extended example in the https://github.com/antkr/ignite-spring-session-demo[example repository, windows="_blank"]. In it, an Ignite node is started with a Spring Session controller.
