#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Release Checker"

on:
  workflow_dispatch:
    inputs:
      extension-name:
        description: 'The name of Ignite Extension'
        required: true
      release-version:
        description: 'THe Extension release version'
        required: true

#jobs:
#  log-the-inputs:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          echo "Log level: $LEVEL"
#          echo "Tags: $TAGS"
#          echo "Environment: $ENVIRONMENT"
#        env:
#          LEVEL: ${{ github.event.inputs.logLevel }}
#          TAGS: ${{ github.event.inputs.tags }}
#          ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  deploy:
    if: github.repository == 'apache/ignite'
    name: "Deploy Apache Ignite"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: apache.snapshots.https
          server-username: NEXUS_USER
          server-password: NEXUS_PW
      - name: Deploy
        run: ./mvnw deploy -Pcheckstyle -DskipTests -Dmaven.javadoc.skip=true -B -V
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
